# SPDX-License-Identifier: MIT-0
---
- name: Update system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install RetroPie dependencies
  ansible.builtin.apt:
    name: "{{ retropie_dependencies }}"
    state: present
