#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Rue Asha
  description: >-
    Provision a Proxmox QEMU VM by cloning an existing template and
    configuring hardware + cloud-init.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - proxmox
    - vm
    - qemu
    - provisioning
    - cloudinit

dependencies: []
