# The Terraform -> Ansible handoff.
#
# Terraform renders the Ansible inventory directly. The alternative -- the
# `ansible/ansible` provider plus the cloud.terraform inventory plugin -- was
# the original design (D7) and is not usable here: cloud.terraform 4.0.0, its
# latest release, calls `get_bin_path(..., required=True)`, and ansible-core
# 2.21 removed that argument. The plugin fails to parse the inventory outright.
#
# Rendering has upsides beyond dodging that: no extra collection, no extra
# provider, no dependency on readable Terraform state at inventory time, and
# the inventory is a plain greppable file that shows up in diffs next to the
# tfvars change that caused it.
#
# The file is committed. `local_file` compares content on every plan, so a
# hand-edit or a stale checkout shows up as drift rather than being silently
# tolerated.

locals {
  # Service groups, derived from the host catalogue.
  lxc_groups = distinct(flatten([for h in var.lxc_hosts : h.groups]))
  vm_groups  = distinct(flatten([for h in var.vm_hosts : h.groups]))

  # Reproduces the pre-Terraform group hierarchy exactly:
  #   <service> -> lxc_container_proxmox | vm_proxmox -> proxmox_guest
  # so every existing file under inventory/group_vars and inventory/host_vars
  # keeps resolving to the same hosts with no edits.
  ansible_inventory = {
    all = {
      children = {
        proxmox_node = {
          hosts = {
            (var.pve_node_inventory_name) = {
              ansible_host = var.pve_node_ip
              ansible_user = var.pve_ssh_username
            }
          }
        }

        proxmox_guest = {
          children = {
            lxc_container_proxmox = {
              children = {
                for g in local.lxc_groups : g => {
                  hosts = {
                    for name, cfg in var.lxc_hosts : name => {
                      ansible_host = module.lxc[name].ipv4_address
                      ansible_user = var.guest_ansible_user
                      # Consumed by roles/proxmox_lxc_tun, which edits
                      # /etc/pve/lxc/<ctid>.conf on the node. Terraform is the
                      # source of truth for the container ID; this replaces the
                      # old `id: {{ ansible_host.split('.')[-1] }}` derivation
                      # that welded the address plan to container IDs.
                      lxc_ctid = module.lxc[name].vmid
                    } if contains(cfg.groups, g)
                  }
                }
              }
            }

            vm_proxmox = {
              children = {
                for g in local.vm_groups : g => {
                  hosts = {
                    for name, cfg in var.vm_hosts : name => {
                      ansible_host = module.vm[name].ipv4_address
                      ansible_user = var.guest_ansible_user
                    } if contains(cfg.groups, g)
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

resource "local_file" "ansible_inventory" {
  filename = "${path.root}/../../../ansible/inventory/00-terraform.yml"

  # yamlencode rather than a template: the nesting is generated, and hand-rolled
  # indentation in a heredoc is exactly where this would break silently.
  content = <<-EOT
    ---
    # GENERATED BY TERRAFORM -- DO NOT EDIT.
    # Source of truth: terraform/environments/homelab/hosts.auto.tfvars
    # Regenerate with: terraform -chdir=terraform/environments/homelab apply
    ${yamlencode(local.ansible_inventory)}
  EOT

  file_permission = "0644"
}
