#SPDX-License-Identifier: MIT-0
---
- name: Update system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
  register: apt_update

- name: Install Pi-hole dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - wget
      - sqlite3
    state: present
